version: '3'
services:
  backend:
    build: .
    container_name: ctf_app
    restart: always
    command: python server/run.py
    depends_on:
      - mysql
    volumes:
      - ./src:/usr/src/app/src/
      - ./server:/usr/src/app/server/
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: mysql://user:pass@ctf_mysql/ctf
      ADMIN_TOKEN: secret
      HOST_IP: 192.168.1.234
  proxy:
    container_name: ctf_proxy
    image: nginx
    restart: always
    depends_on:
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/443/:/etc/nginx/conf.d/
      - ./ssl:/etc/ssl/private/
  mysql:
    image: mysql:8.0.18
    container_name: ctf_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: ctf
      MYSQL_USER: user
      MYSQL_PASSWORD: pass